config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'
  
  resources :tests do
    resources :questions, shallow:true, except: :index do
      resources :answers, shallow: true
    end

    member do 
      post :start
    end
  end
  

  resources :test_passages, only: %i[show update] do 
    member do
      get :result
    end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :question

    scope :correct, -> { where(correct: true) }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :tests
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
    has_many :questions
    has_many :tests_passages
    has_many :users, through: :test_passages
    belongs_to :category, optional: true

    validates :title,   presence: true,
                        uniqueness: true
    validates :level,   numericality: { only_integer: true }, allow_nil: true
    validate :validate_max_level

    scope :easy, -> { where(level: 0..1) }
    scope :medium, -> { where(level: 2..4) }
    scope :hard, -> { where(level: 5..10) }

    def validate_max_level
        errors.add(:level) if level.to_i > 10
    end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :question, optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_validation :before_validation_set_next_question, on: :update

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    self.question = next_question
    save
  end

  def completed?
    question.nil?
  end

  private 

  def before_validation_set_first_question
    self.question = test.questions.first if test.present?
  end

  def before_validation_set_next_question
    self.question = test.questions.order(:id).where('id > ?', self.question.id).first
  end

  def correct_answer?(answer_ids)
    count_correct_answer = correct_answers.count
    count_correct_answer == correct_answers.where(id: answer_ids).count && count_correct_answer == answer_ids.count
  end

  def correct_answers
    question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', self.question.id).first
  end

end

app/models/tests_user.rb
class  TestsUser < ApplicationRecord
    belongs_to :test
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :test_passages, dependent: :destroy
    has_many :tests, through: :test_passages

    def test_passage(test)
        test_passages.order(id: :desc).find_by(test_id: test.id)
    end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

    before_action :find_question, only: [:new, :create]
    before_action :find_answer, only: [:show, :edit, :update, :destroy]

    def show
    end

    def new
        @answer = @question.answers.new
    end

    def edit
    end

    def create
        @answer = Answer.new(answer_params)
        respond_to do |format|
            if @answer.save
                redirect_to @answer, notice: 'Answer was successfully created.'
            else
                render :new
            end
        end
    end

    def destroy 
        @answer.destroy
        riderect_to @answer.question
    end

    private

    def find_question
        @question = Question.find(params[:question_id])
    end

    def find_answer
        @answer = Answer.find(params[:id])
    end

    def answer_params
        params.require(:answer).permit(:body, :correct)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    before_action :find_question, only: %i[show destroy edit update]
    before_action :find_test, only: %i[create new]
  
    def show
    end
  
    def new
      @question = @test.questions.new
    end
  
    def create
      @question = @test.questions.new(question_params)
  
      if @question.save
        redirect_to question_path(@question)
      else
        render :new
      end
  end
  
    def edit
    end
  
    def update
      if @question.update(question_params)
        # redirect_to admin_question_path(@question)
      else
        render :new
      end
    end
  
    def destroy
      @question.destroy
    #   redirect_to admin_tests_path
    end
  
  
    private
  
    def find_test
      @test = Test.find(params[:test_id])
    end
  
    def find_question
      @question = Question.find(params[:id])
    end
  
    def question_params
      params.require(:question).permit(:body)
    end
  end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController

    before_action :set_test_passage, only: %i[show result update]

    def show
        
    end

    def result
    end

    def update
        @test_passage.accept!(params[:answer_ids])
        if @test_passage.completed?
            redirect_to result_test_passage_path(@test_passage)
        else
            render :show
        end
    end

    private

    def set_test_passage
        @test_passage = TestPassage.find(params[:id])
    end
    
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :find_test, only: %i[start edit update destroy show]
  before_action :find_user, only: %i[start]

  def show

  end

  def index
    @tests = Test.all
  end
  
  def def(_new)
    render :new
  end

  def create
    test = Test.create(test_params)
  end

  def update
    if @test.update(test_params)
      redirect_to @test
    else
      render :edit
    end
  end

  def destroy
    @test.destroy
    redirect_to test_path
  end

  def start
    @user.tests.push(@test)
    redirect_to @user.test_passage(@test)
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end

  def test_params
    params.requre(:test).permit(:title, :level)
  end

  def find_user
    # @user = User.find(params[:user_id])
    @user = User.first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/answers/_answer.html.erb
<li>
    <%= answer.body %><br>
    <%= link_to 'Show', answer_path(answer) %>
    <%= link_to 'Edit', edit_answer_path(answer) %>
    <%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %>
</li>

app/views/answers/edit.html.erb
<h1> New answer </h1>
<%= form_with model:[@question, @answer] do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.label :correct%>
    <%= f.check_box :correct, answer_correct %>
  <%= f.submit %>
<% end %>

app/views/answers/new.html.erb
<h1> New answer </h1>
<%= form_with model:[@question, @answer] do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body %>
   <%= f.label :correct%>
    <%= f.check_box :correct, answer_correct %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/_question.html.erb
<li>
  <%= link_to question.body, question_path(question) %> |
  <%= link_to t('edit'), edit_question_path(question) %> |
</li>

app/views/questions/new.html.erb
<h1><%= form_header(@question) %></h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<h1><%=  @question.test.title %>Question</h1>

<p><%= @question.body%></p>

<h2>Answers</h2>
<%= link_to 'New answer', new_question_answer_path(@question) %>
<ol>
    <%= render @question.answers %>
</ol>

app/views/test_passages/resul.html.erb
<h1><%= @test_passage.test.title %> test</h1>

<% if @test_passage.passed? %>
	<p class="success">Completed successfully: <%= @test_passage.score %>%</p>
<% else %>
	<p class="fail">Failed: <%= @test_passage.score %>%</p>
<% end %>

app/views/test_passages/show.html.erb
<h1>Passing the <%= @test_passage.test.title  %></h1>
<h2><%= @test_passage.question.body %></h2>


<div><%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form|%>
    <%= form.collection_check_boxes :answer_ids, @test_passage.question.answers, :id, :body, include_hidden: false do |b| %>
        <li>
            <%= b.check_box id: "answer_ids_#(b.object.id)" %>
            <%= b.label %>
        </li>
    <% end %>
    <%= form.submit "next" %>
<% end %>
</div>